name: build

on:
  push:
    tags:
      - "v*"

jobs:
  build_and_upload:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            bin: yeah-linux-amd64
          - os: windows-latest
            goos: windows
            bin: yeah-windows-amd64.exe
          - os: macos-latest
            goos: darwin
            bin: yeah-darwin-amd64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: build
        shell: bash
        run: |
          GOOS='${{ matrix.goos }}' GOARCH='amd64' CGO_ENABLED=0 go build -o '${{ matrix.bin }}' cmd/main.go

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.bin }}
          path: ${{ matrix.bin }}
          if-no-files-found: error

  create_release_and_upload_assets:
    needs: build_and_upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: upload linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/yeah-linux-amd64/yeah-linux-amd64
          asset_name: yeah-linux-amd64
          asset_content_type: application/octet-stream

      - name: upload macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/yeah-darwin-amd64/yeah-darwin-amd64
          asset_name: yeah-darwin-amd64
          asset_content_type: application/octet-stream

      - name: upload windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/yeah-windows-amd64.exe/yeah-windows-amd64.exe
          asset_name: yeah-windows-amd64.exe
          asset_content_type: application/vnd.microsoft.portable-executable

  upload_telegram:
    needs: create_release_and_upload_assets
    runs-on: ubuntu-latest
    steps:
      - name: Post Files to Telegram
        uses: xireiki/channel-post@v2
        with:
          bot_token: ${{ secrets.BOT_TOKEN }}
          chat_id: ${{ secrets.CHAT_ID }}
          context: "New release"
          path: artifacts/yeah-*
          parse_mode: None
          method: sendFile
